import React, { useState } from 'react';
import { AdPlan } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend, BarChart, Bar, XAxis, YAxis } from 'recharts';
import { Download, TrendingUp, ShieldAlert, Target, Search, MessageSquare, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface Props {
  plan: AdPlan;
  onOpenChat: () => void;
}

const COLORS = ['#0ea5e9', '#8b5cf6', '#f43f5e', '#10b981', '#f59e0b'];

export const PlanDashboard: React.FC<Props> = ({ plan, onOpenChat }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'roi' | 'swot' | '4p' | 'insight'>('overview');

  const pieData = plan.allocations.map(a => ({ name: a.name, value: a.budget }));

  const TabButton = ({ id, label, icon: Icon }: any) => (
    <button
      onClick={() => setActiveTab(id)}
      className={`flex items-center gap-2 px-4 py-3 font-medium transition-colors border-b-2 ${
        activeTab === id 
          ? 'border-brand-600 text-brand-600 bg-brand-50' 
          : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
      }`}
    >
      <Icon size={18} />
      {label}
    </button>
  );

  const handleExportMarkdown = () => {
    const { name, totalBudget, duration, regions, allocations, analysis } = plan;
    
    const allocationsTable = allocations.map(item => 
      `| ${item.name} | ${item.type} | ${item.percentage}% | ¥${item.budget.toLocaleString()} | ${item.reasoning} |`
    ).join('\n');

    const markdownContent = `
# ${name}

**总预算:** ¥${totalBudget.toLocaleString()}  
**投放周期:** ${duration}  
**覆盖区域:** ${regions.join(', ')}

## 1. 媒体投放组合策略

| 媒体名称 | 类型 | 占比 | 预算 | 推荐理由 |
|---|---|---|---|---|
${allocationsTable}

## 2. 市场与竞品洞察
${analysis.competitorInsight}

## 3. 投资回报率 (ROI) 预估
${analysis.roi}

## 4. SWOT 分析
${analysis.swot}

## 5. 4P 营销策略建议
${analysis.marketing4p}

---
*Generated by OOH小助手*
    `.trim();

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${name}_投放方案.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="max-w-6xl mx-auto p-4 space-y-6">
      {/* Header */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{plan.name}</h1>
          <p className="text-gray-500 mt-1">总预算: ¥{plan.totalBudget.toLocaleString()} | 周期: {plan.duration} | 区域: {plan.regions.join(', ')}</p>
        </div>
        <div className="flex gap-2">
          {/* Removed Share Button */}
          <button 
            onClick={handleExportMarkdown}
            className="flex items-center gap-2 px-4 py-2 bg-brand-600 text-white rounded-lg hover:bg-brand-700 shadow-md transition-all hover:-translate-y-0.5"
          >
            <FileText size={16} /> 导出 Markdown
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Visuals & Allocations */}
        <div className="lg:col-span-1 space-y-6">
           {/* Budget Distribution */}
           <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
              <h3 className="font-bold text-gray-800 mb-4">预算分配占比</h3>
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={pieData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={80}
                      paddingAngle={5}
                      dataKey="value"
                    >
                      {pieData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(value: number) => `¥${value.toLocaleString()}`} />
                    <Legend verticalAlign="bottom" height={36}/>
                  </PieChart>
                </ResponsiveContainer>
              </div>
           </div>

           {/* Media List */}
           <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
             <h3 className="font-bold text-gray-800 mb-4">媒体明细</h3>
             <div className="space-y-4">
               {plan.allocations.map((item, idx) => (
                 <div key={idx} className="p-3 bg-gray-50 rounded-lg border border-gray-200">
                   <div className="flex justify-between items-start mb-1">
                     <span className="font-semibold text-brand-900">{item.name}</span>
                     <span className="text-sm font-bold text-brand-600">{item.percentage}%</span>
                   </div>
                   <div className="text-xs text-gray-500 mb-2">{item.type}</div>
                   <div className="text-sm text-gray-600 bg-white p-2 rounded border border-gray-100 text-xs">
                     {item.reasoning}
                   </div>
                 </div>
               ))}
             </div>
           </div>
        </div>

        {/* Right Column: Analysis Tabs */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden min-h-[600px] flex flex-col">
            <div className="flex border-b border-gray-200 overflow-x-auto">
              <TabButton id="overview" label="品牌洞察" icon={Search} />
              <TabButton id="roi" label="ROI评估" icon={TrendingUp} />
              <TabButton id="swot" label="SWOT分析" icon={ShieldAlert} />
              <TabButton id="4p" label="4P营销" icon={Target} />
            </div>

            <div className="p-6 flex-grow overflow-y-auto custom-markdown">
              {activeTab === 'overview' && (
                <div>
                   <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-brand-700">
                     <Search size={24}/> 市场与竞品洞察 (Real-time)
                   </h2>
                   <div className="prose prose-blue max-w-none">
                     <ReactMarkdown>{plan.analysis.competitorInsight}</ReactMarkdown>
                   </div>
                </div>
              )}
              {activeTab === 'roi' && (
                <div>
                  <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-green-700">
                    <TrendingUp size={24}/> 投资回报率 (ROI) 预估
                  </h2>
                  <div className="prose prose-green max-w-none">
                    <ReactMarkdown>{plan.analysis.roi}</ReactMarkdown>
                  </div>
                </div>
              )}
              {activeTab === 'swot' && (
                <div>
                   <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-purple-700">
                    <ShieldAlert size={24}/> 深度 SWOT 分析
                  </h2>
                  <div className="prose prose-purple max-w-none">
                    <ReactMarkdown>{plan.analysis.swot}</ReactMarkdown>
                  </div>
                </div>
              )}
              {activeTab === '4p' && (
                <div>
                   <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-orange-700">
                    <Target size={24}/> 4P 营销策略建议
                  </h2>
                  <div className="prose prose-orange max-w-none">
                    <ReactMarkdown>{plan.analysis.marketing4p}</ReactMarkdown>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      
      {/* Floating Chat Button */}
      <button 
        onClick={onOpenChat}
        className="fixed bottom-8 right-8 bg-brand-600 text-white p-4 rounded-full shadow-2xl hover:bg-brand-700 transition-transform transform hover:scale-110 z-50 flex items-center gap-2"
      >
        <MessageSquare size={24} />
        <span className="font-bold">咨询专家 Tom</span>
      </button>
    </div>
  );
};