import React, { useState, useMemo } from 'react';
import { AdPlan, MediaAllocation } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, Legend, Sector } from 'recharts';
import { TrendingUp, ShieldAlert, Target, Search, MessageSquare, FileText, Image as ImageIcon, Save, RefreshCw, Printer, FileJson } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface Props {
  plan: AdPlan;
  onOpenChat: () => void;
  onSavePlan: (plan: AdPlan) => void;
  onReset: () => void;
  onUpdatePlan: (plan: AdPlan) => void;
}

const COLORS = ['#0ea5e9', '#8b5cf6', '#f43f5e', '#10b981', '#f59e0b', '#6366f1', '#ec4899'];

const renderActiveShape = (props: any) => {
  const { cx, cy, innerRadius, outerRadius, startAngle, endAngle, fill, payload, percent, value } = props;

  return (
    <g>
      <text x={cx} y={cy - 12} dy={8} textAnchor="middle" fill="#6b7280" className="text-xs font-medium">
        {payload.name}
      </text>
      <text x={cx} y={cy + 12} dy={8} textAnchor="middle" fill={fill} className="text-lg font-bold">
        {`¥${(value as number).toLocaleString()}`}
      </text>
      <text x={cx} y={cy + 32} dy={8} textAnchor="middle" fill="#9ca3af" className="text-xs">
        {`(${(percent * 100).toFixed(1)}%)`}
      </text>
      <Sector
        cx={cx}
        cy={cy}
        innerRadius={innerRadius}
        outerRadius={outerRadius + 8}
        startAngle={startAngle}
        endAngle={endAngle}
        fill={fill}
      />
      <Sector
        cx={cx}
        cy={cy}
        startAngle={startAngle}
        endAngle={endAngle}
        innerRadius={outerRadius + 10}
        outerRadius={outerRadius + 14}
        fill={fill}
      />
    </g>
  );
};

export const PlanDashboard: React.FC<Props> = ({ plan, onOpenChat, onSavePlan, onReset, onUpdatePlan }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'roi' | 'swot' | '4p' | 'insight'>('overview');
  const [activeIndex, setActiveIndex] = useState(0);
  const [isSorted, setIsSorted] = useState(false);
  const [isSaved, setIsSaved] = useState(false);

  const pieData = useMemo(() => {
    const data = plan.allocations.map(a => ({ name: a.name, value: a.budget, type: a.type }));
    if (isSorted) {
      return [...data].sort((a, b) => b.value - a.value);
    }
    return data;
  }, [plan.allocations, isSorted]);

  const onPieEnter = (_: any, index: number) => {
    setActiveIndex(index);
  };

  const handleSave = () => {
    onSavePlan(plan);
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportJSON = () => {
    const jsonString = JSON.stringify(plan, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${plan.name}_${new Date().toLocaleDateString().replace(/\//g, '-')}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportMarkdown = () => {
    const { name, totalBudget, duration, regions, allocations, analysis } = plan;
    
    // Create table with specifications column
    const allocationsTable = allocations.map(item => 
      `| ${item.name} | ${item.type} | ${item.specifications || '标准规格'} | ${item.percentage}% | ¥${item.budget.toLocaleString()} | ${item.reasoning.replace(/\n/g, ' ')} |`
    ).join('\n');

    const markdownContent = `
# ${name} - 户外媒体投放方案

**生成日期:** ${new Date(plan.createdAt).toLocaleDateString()}  
**总预算:** ¥${totalBudget.toLocaleString()}  
**投放周期:** ${duration}  
**覆盖区域:** ${regions.join(', ')}

---

## 1. 媒体投放组合策略

| 媒体名称 | 类型 | 规格/点位 | 占比 | 预算 | 推荐理由 |
|---|---|---|---|---|---|
${allocationsTable}

---

## 2. 竞品分析 (Competitor Analysis)
${analysis.competitorInsight}

---

## 3. 投资回报率 (ROI) 预估
${analysis.roi}

---

## 4. SWOT 分析
${analysis.swot}

---

## 5. 4P 营销策略建议
${analysis.marketing4p}

---
*Generated by OOH小助手 - 您的户外媒体投放专家*
    `.trim();

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${name}_投放方案_${new Date().toLocaleDateString().replace(/\//g, '-')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleAllocationChange = (index: number, field: keyof MediaAllocation, value: any) => {
    const newAllocations = [...plan.allocations];
    
    if (field === 'percentage') {
        let newPercentage = Math.min(100, Math.max(0, Number(value)));
        
        // Calculate sum of budgets of ALL OTHER items
        const otherBudget = plan.allocations.reduce((sum, item, i) => i === index ? sum : sum + item.budget, 0);
        let newBudget = newAllocations[index].budget;

        if (otherBudget === 0) {
            // If there are no other items to balance against, we fallback to simple scaling of the current total.
            // Note: If this is the only item, percentage is forced to 100% mathematically.
            newBudget = Math.round(plan.totalBudget * (newPercentage / 100));
        } else {
            // Smart Formula: Calculate what budget is needed so that it equals P% of the NEW total.
            // Budget / (Budget + Other) = P / 100
            // Budget = Other * (P / (100 - P))
            
            // Cap percentage to avoid division by zero
            if (newPercentage >= 99.9) newPercentage = 99.9;
            
            newBudget = Math.round(otherBudget * (newPercentage / (100 - newPercentage)));
        }
        
        newAllocations[index] = {
            ...newAllocations[index],
            budget: newBudget
        };
        
        // Recalculate Total Budget to be the sum of all components
        const newTotalBudget = newAllocations.reduce((sum, item) => sum + item.budget, 0);

        // Normalize all percentages based on the new total to keep data consistent
        if (newTotalBudget > 0) {
            newAllocations.forEach((item, i) => {
                newAllocations[i].percentage = Number(((item.budget / newTotalBudget) * 100).toFixed(1));
            });
        }
        
        onUpdatePlan({
            ...plan,
            totalBudget: newTotalBudget,
            allocations: newAllocations
        });

    } else if (field === 'budget') {
        const newBudget = Math.max(0, Number(value));
        newAllocations[index] = {
            ...newAllocations[index],
            budget: newBudget
        };
        
        // Recalculate Total Budget
        const newTotalBudget = newAllocations.reduce((sum, item) => sum + item.budget, 0);
        
        // Recalculate all percentages
        if (newTotalBudget > 0) {
            newAllocations.forEach((item, i) => {
                newAllocations[i].percentage = Number(((item.budget / newTotalBudget) * 100).toFixed(1));
            });
        }

        onUpdatePlan({
            ...plan,
            totalBudget: newTotalBudget,
            allocations: newAllocations
        });
    } else {
        newAllocations[index] = {
            ...newAllocations[index],
            [field]: value
        };
        onUpdatePlan({ ...plan, allocations: newAllocations });
    }
  };

  const TabButton = ({ id, label, icon: Icon }: any) => (
    <button
      onClick={() => setActiveTab(id)}
      className={`flex items-center gap-2 px-4 py-3 font-medium transition-colors border-b-2 ${
        activeTab === id 
          ? 'border-brand-600 text-brand-600 bg-brand-50' 
          : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
      }`}
    >
      <Icon size={18} />
      {label}
    </button>
  );

  return (
    <div className="max-w-6xl mx-auto p-4 space-y-6">
      {/* Header */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{plan.name}</h1>
          <p className="text-gray-500 mt-1">总预算: ¥{plan.totalBudget.toLocaleString()} | 周期: {plan.duration} | 区域: {plan.regions.join(', ')}</p>
        </div>
        <div className="flex flex-wrap gap-2 print:hidden">
          <button 
            onClick={onReset}
            className="flex items-center gap-2 px-3 py-2 border border-gray-300 text-gray-700 bg-white rounded-lg hover:bg-red-50 hover:text-red-600 hover:border-red-200 shadow-sm transition-all"
            title="清空当前方案并返回配置"
          >
            <RefreshCw size={16} /> 重置方案
          </button>
          
           <div className="h-8 w-[1px] bg-gray-300 mx-1"></div>

           <button 
            onClick={handleExportJSON}
            className="flex items-center gap-2 px-3 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-all"
            title="导出 JSON"
          >
            <FileJson size={16} /> JSON
          </button>
           <button 
            onClick={handleExportMarkdown}
            className="flex items-center gap-2 px-3 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-all"
            title="导出 Markdown"
          >
            <FileText size={16} /> MD
          </button>
          <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-3 py-2 bg-gray-800 text-white rounded-lg hover:bg-gray-900 shadow-md transition-all"
            title="打印或保存为 PDF"
          >
            <Printer size={16} /> 打印/PDF
          </button>
          
          <div className="h-8 w-[1px] bg-gray-300 mx-1"></div>

          <button 
            onClick={handleSave}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-white shadow-md transition-all ${
              isSaved ? 'bg-green-600' : 'bg-brand-600 hover:bg-brand-700'
            }`}
          >
            <Save size={16} /> {isSaved ? '已保存!' : '保存方案'}
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Visuals & Allocations */}
        <div className="lg:col-span-1 space-y-6">
           {/* Budget Distribution */}
           <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 print:break-inside-avoid">
              <div className="flex justify-between items-center mb-4">
                <h3 className="font-bold text-gray-800">预算分配占比</h3>
                <button 
                  onClick={() => setIsSorted(!isSorted)}
                  className="text-xs text-brand-600 bg-brand-50 px-2 py-1 rounded hover:bg-brand-100 transition-colors print:hidden"
                >
                   {isSorted ? '恢复默认排序' : '按预算排序'}
                </button>
              </div>
              <div className="h-72 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart onClick={() => setIsSorted(!isSorted)}>
                    <Pie
                      activeIndex={activeIndex}
                      activeShape={renderActiveShape}
                      data={pieData}
                      cx="50%"
                      cy="50%"
                      innerRadius={65}
                      outerRadius={85}
                      paddingAngle={4}
                      dataKey="value"
                      onMouseEnter={onPieEnter}
                      className="cursor-pointer outline-none"
                    >
                      {pieData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} stroke="none" />
                      ))}
                    </Pie>
                    <Legend verticalAlign="bottom" height={36} iconType="circle" />
                  </PieChart>
                </ResponsiveContainer>
              </div>
           </div>

           {/* Media List - Editable */}
           <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 print:break-inside-avoid">
             <div className="flex justify-between items-center mb-4">
                 <h3 className="font-bold text-gray-800">媒体明细 (可编辑)</h3>
                 <span className="text-xs text-gray-400 print:hidden">点击数值即可修改</span>
             </div>
             <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar print:max-h-none print:overflow-visible">
               {plan.allocations.map((item, idx) => (
                 <div key={idx} className="p-3 bg-gray-50 rounded-lg border border-gray-200 hover:border-brand-200 transition-colors group">
                   <div className="flex gap-3">
                     {item.imageUrl && (
                       <a 
                         href={item.imageUrl} 
                         target="_blank" 
                         rel="noopener noreferrer" 
                         className="shrink-0 group relative block print:hidden"
                       >
                         <img 
                           src={item.imageUrl} 
                           alt={item.name} 
                           className="w-16 h-16 object-cover rounded-md border border-gray-200 shadow-sm" 
                         />
                       </a>
                     )}
                     <div className="flex-1 min-w-0">
                       <div className="flex justify-between items-start mb-2 gap-2">
                         <div className="font-semibold text-brand-900 truncate pr-2 flex-1">{item.name}</div>
                         <div className="flex items-center gap-1 shrink-0 bg-white border border-gray-200 rounded px-1.5 py-0.5">
                            <input
                                type="number"
                                value={item.percentage}
                                onChange={(e) => handleAllocationChange(idx, 'percentage', e.target.value)}
                                className="w-12 text-right text-sm font-bold text-brand-600 focus:outline-none focus:ring-0 border-none p-0 bg-transparent"
                            />
                            <span className="text-xs font-bold text-gray-400">%</span>
                         </div>
                       </div>
                       
                       <div className="flex items-center gap-2 mb-2 text-xs text-gray-500">
                          <span className="px-1.5 py-0.5 bg-gray-200 rounded text-gray-600">{item.type}</span>
                          <div className="flex items-center gap-1 bg-white px-1.5 py-0.5 rounded border border-gray-200">
                            <span>¥</span>
                            <input
                                type="number"
                                value={item.budget}
                                onChange={(e) => handleAllocationChange(idx, 'budget', e.target.value)}
                                className="w-20 focus:outline-none focus:ring-0 border-none p-0 text-gray-600 bg-transparent"
                            />
                          </div>
                       </div>

                       <textarea
                         value={item.reasoning}
                         onChange={(e) => handleAllocationChange(idx, 'reasoning', e.target.value)}
                         className="w-full text-sm text-gray-600 bg-white p-2 rounded border border-gray-100 text-xs leading-relaxed resize-none focus:ring-1 focus:ring-brand-500 focus:border-brand-500 transition-all"
                         rows={3}
                       />
                     </div>
                   </div>
                 </div>
               ))}
             </div>
           </div>
        </div>

        {/* Right Column: Analysis Tabs */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden min-h-[600px] flex flex-col print:min-h-0 print:shadow-none print:border-none">
            <div className="flex border-b border-gray-200 overflow-x-auto print:hidden">
              <TabButton id="overview" label="品牌洞察" icon={Search} />
              <TabButton id="roi" label="ROI评估" icon={TrendingUp} />
              <TabButton id="swot" label="SWOT分析" icon={ShieldAlert} />
              <TabButton id="4p" label="4P营销" icon={Target} />
            </div>

            <div className="p-6 flex-grow overflow-y-auto custom-markdown print:overflow-visible print:h-auto">
              {/* Print View: Show all sections */}
              <div className="hidden print:block space-y-8">
                 <section>
                    <h2 className="text-xl font-bold mb-4">1. 市场与竞品洞察</h2>
                    <ReactMarkdown>{plan.analysis.competitorInsight}</ReactMarkdown>
                 </section>
                 <section>
                    <h2 className="text-xl font-bold mb-4">2. 投资回报率 (ROI) 预估</h2>
                    <ReactMarkdown>{plan.analysis.roi}</ReactMarkdown>
                 </section>
                 <section>
                    <h2 className="text-xl font-bold mb-4">3. SWOT 分析</h2>
                    <ReactMarkdown>{plan.analysis.swot}</ReactMarkdown>
                 </section>
                 <section>
                    <h2 className="text-xl font-bold mb-4">4. 4P 营销策略建议</h2>
                    <ReactMarkdown>{plan.analysis.marketing4p}</ReactMarkdown>
                 </section>
              </div>

              {/* Web View: Show active tab */}
              <div className="print:hidden">
                  {activeTab === 'overview' && (
                    <div>
                       <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-brand-700">
                         <Search size={24}/> 市场与竞品洞察 (Real-time)
                       </h2>
                       <div className="prose prose-blue max-w-none">
                         <ReactMarkdown>{plan.analysis.competitorInsight}</ReactMarkdown>
                       </div>
                    </div>
                  )}
                  {activeTab === 'roi' && (
                    <div>
                      <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-green-700">
                        <TrendingUp size={24}/> 投资回报率 (ROI) 预估
                      </h2>
                      <div className="prose prose-green max-w-none">
                        <ReactMarkdown>{plan.analysis.roi}</ReactMarkdown>
                      </div>
                    </div>
                  )}
                  {activeTab === 'swot' && (
                    <div>
                       <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-purple-700">
                        <ShieldAlert size={24}/> 深度 SWOT 分析
                      </h2>
                      <div className="prose prose-purple max-w-none">
                        <ReactMarkdown>{plan.analysis.swot}</ReactMarkdown>
                      </div>
                    </div>
                  )}
                  {activeTab === '4p' && (
                    <div>
                       <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-orange-700">
                        <Target size={24}/> 4P 营销策略建议
                      </h2>
                      <div className="prose prose-orange max-w-none">
                        <ReactMarkdown>{plan.analysis.marketing4p}</ReactMarkdown>
                      </div>
                    </div>
                  )}
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {/* Floating Chat Button */}
      <button 
        onClick={onOpenChat}
        className="fixed bottom-8 right-8 bg-brand-600 text-white p-4 rounded-full shadow-2xl hover:bg-brand-700 transition-transform transform hover:scale-110 z-50 flex items-center gap-2 print:hidden"
      >
        <MessageSquare size={24} />
        <span className="font-bold">咨询专家 Tom</span>
      </button>
    </div>
  );
};